# Generated by Django 4.0.5 on 2022-07-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0011_project_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
